### ISSUE TITLE
Roadmap 2020

### ISSUE THREAD

**Issue by mahmoud** [mahmoud/glom#113]
With 19.10.0 out, here are the priorities targeted for 2019Q4 or 2020Q1:

1. [x] **match-mode** (#94): get it a bit o polish and under real use (more test cases, see how it feels, what defaults feel right)
   * Related: #92
2. [x] **New error discipline** (#112): all glom errors should have a path and yield a tidy stack with clear debugging steps. This is critical for validation errors from match-mode (and `Check()` if it's not obsolete)
   * Related: #88, #64, #42
3.  [ ] **Traverse** (#45): Recursion and context-free application, as in [remap](https://sedimental.org/remap.html).
    * Related: #89, #39

All of the above could combine (likely with attrs, already a dependency) to create a very lightweight and flexible value object system.

We may also want to look into compiling/macros (#65, #57, #36). 

Let's get it!

**Comment by kurtbrose** [comment]
playing around with pattern matching on top of match

```python
Switch(
    (Or(None, int, float, str, unicode, basestring, bool), T),
    (Or(list, tuple), [recurse]),
    (And, (T.children[-1], recurse)),
)
```

```python
   def glomit(self):
       for match, auto in self.pairs:
           try:
               Match(match).glomit(target, scope)
               break
            except GlomError:
               pass
             else:
                return Auto(auto).glomit(target, scope)
         raise GlomError('didnt match any patterns')
```

maybe pull could be kind of an inverse of Fill
```python
(Pull( {'a': [S['b']]}), Fill({'a': [S['b']}))
```
is basically a no-op -- pull extracts the thing there to `S['b']` and fill puts it back

**Comment by mahmoud** [comment]
Next up:

- [ ] prepr
- [ ] star (may replace traverse)
- [ ] multierror
- [ ] T arithmetic

**Comment by mahmoud** [comment]
I believe all of these have been addressed except full recursion a la Traverse. But overall, closing this issue in favor of a future milestone.
