### ISSUE TITLE
v20.7.0

### ISSUE THREAD

**Issue by mahmoud** [mahmoud/glom#165]
Items to discuss, implement, and/or merge before this month's release:

- [x] #94 
- [x] #163 / #159 
- [x] ~#157~ (deferred)
- [x] ~#152~ (deferred due to more testing / repr issue)
- [x] #150 (closes #149)
- [x] #140
- [x] #84 (probs just close)
- [x] ~#154~  (deferred until there's a need for a datastructure with booleans built from `M` expressions)
- [x] #146 (this works now, right?)
- [x] #174 `S(a=T.a)` style capture 
- [x] recursive bbrepr
- [x] `Literal` becomes `Val` alias
- [x] #171 
- [x] ~lowercase `match()` or `match` kwarg~ (defer until we've used Match() more)
- [x] #170  

All of the above are pretty much there. The following are ideas for docs:

- [x] update the part of the FAQ that talks about schema
- [x] More links to the new exceptions & debugging doc
- [x] Exceptions also explain stack-trace-formatting
- [x] rewrite JSON tree walk snippet to use Switch once merged

**Comment by kurtbrose** [comment]
I'd propose that we try to cut out anything that isn't part of the "pattern match" cluster, to get to `*` and `**` paths ASAP since I think those will be high impact

**Comment by kurtbrose** [comment]
oh yea, I should add the "(A.t, ..., S.t)" target-reset idiom to snippets

**Comment by kurtbrose** [comment]
just thinking through functionality for the release -- there's that one bug with the error handling, which is fixed by https://github.com/mahmoud/glom/pull/170 (although some other behavioral changes are along for the ride)

the other big area is repr -- reprlib doesn't support recursion properly; our own custom repr might also be nice if it had a way of doing injected sofar -- so `...` could be used to replace other bits of data structured


```python
Spec: Match(Switch({'a': 1, 'b': 2}))
Spec: Switch({'a': 1, 'b': 2})
Spec: 'a'
Spec: 1
``` 

following a simple rule of "things already repr()'d become ..." might instead become

```python
Spec: Match(...)
Spec: Switch({...: ..., 'b': 2})
Spec: 'a'
Spec1
```

maybe atomic integers / strings get a pass on `...` substitution

```python
Spec: Match(...)
Spec: Switch({'a': 1, 'b': 2})
Spec: 'a'
Spec1
```

**Comment by mahmoud** [comment]
Shipped :) https://pypi.org/project/glom/20.7.0/
